### ISSUE TITLE
Plugin is Incompatible 

### ISSUE THREAD

**Issue by CReich02** [mterwoord/resharper-genericsinlayhints#1]
The plugin is showing as Incompatible in ReSharper and I am not able to find it on the [JetBrains Plugins](https://plugins.jetbrains.com/search?search=Generic%20inlay) website, I only see the version for Rider there.
![image](https://github.com/mterwoord/resharper-genericsinlayhints/assets/11139609/83829233-31d8-4b02-8cb2-7f82bbca9c18)

**Comment by mterwoord** [comment]
Thanks for reporting. I have some wrong compatibility listed in the newer versions (We're on 0.6 now). Will let you know when I have something new..

**Comment by mterwoord** [comment]
I think it's solved now. Can you check?

**Comment by CReich02** [comment]
Yes, I am able to update now. Thank you for the quick response.
